apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-initial-data-volume
  namespace: {{ .Release.Namespace }}
{{ tuple . "db-initial-data-volume" | include "db.labels" | indent 2 }}
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.db.initialDataHostPath }}
  claimRef:
    name: db-initial-data-pv-claim
    namespace: {{ .Release.Namespace }}