apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-initial-data-pv-claim
  namespace: {{ .Release.Namespace }}
{{ tuple . "db-initial-data-pv-claim" | include "db.labels" | indent 2 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      lies.exposed/name: db-initial-data-volume
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/namespace: {{ .Release.Namespace | quote }}
