apiVersion: v1
data:
  POSTGRES_DB: {{ .Values.db.database }}
  POSTGRES_PASSWORD: "{{ .Values.db.password }}"
  POSTGRES_USER: {{ .Values.db.username }}
  # PGSSLMODE: "require"
  # PGSSLROOTCERT: "./certs/db-ca-certificate.crt"
  # DB_SSL_MODE: "require"
  # DB_SSL_CERT_PATH: "./certs/db-ca-certificate.crt"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  name: db-env
