apiVersion: v1
kind: Service
metadata:
  name: db-nodeport
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: db
    lies.exposed/name: db
spec:
  type: NodePort
  selector:
    lies.exposed/name: db
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: {{ .Values.db.nodePort | default 30001 }}