apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Release.Namespace }}
  labels:
    lies.exposed/name: db
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/namespace: {{ .Release.Namespace | quote }}
    app.kubernetes.io/component: cache
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    lies.exposed/name: db
  type: ClusterIP
  externalIPs:
    - 192.168.54.32
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
