{{- if .Values.agent.enabled }}
apiVersion: v1
data:
{{ tuple . "config/env/agent.env" | include "env.parseFile" | indent 2 }}
kind: ConfigMap
metadata:
  name: agent-env
  namespace: {{ .Release.Namespace }}
{{ tuple . "agent-env" | include "agent.labels" | indent 2 }}
{{- end }}