apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localai-models-pv-claim
  namespace: {{ .Release.Namespace }}
  labels:
    lies.exposed/name: localai-models-pv-claim
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/namespace: {{ .Release.Namespace | quote }}
    app.kubernetes.io/component: cache
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
  selector:
    matchLabels:
      lies.exposed/name: localai-models-volume
      app.kubernetes.io/namespace: {{ .Release.Namespace | quote }}
