apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localai-backends-pv-claim
  namespace: {{ .Release.Namespace }}
{{ tuple . "localai-backends-pv-claim" | include "localai.labels" | indent 2 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
  selector:
    matchLabels:
      lies.exposed/name: localai-backends-volume
      app.kubernetes.io/namespace: {{ .Release.Namespace | quote }}
