apiVersion: v1
kind: PersistentVolume
metadata:
  name: localai-models-volume
  namespace: {{ .Release.Namespace }}
{{ tuple . "localai-models-volume" | include "localai.labels" | indent 2 }}
spec:
  # storageClassName: microk8s-hostpath
  storageClassName: manual
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.localai.modelsHostPath | quote }}
  claimRef:
    name: localai-models-pv-claim
    namespace: {{ .Release.Namespace }}