apiVersion: v1
data:
  DEBUG: "true"
  LOCALAI_LOG_LEVEL: debug
  LOCALAI_THREADS: "4"
  LOCALAI_API_KEY: {{ .Values.localai.openAIApiKey | quote }}
  # LOCALAI_SINGLE_ACTIVE_BACKEND: "true"
kind: ConfigMap
metadata:
  name: localai-env
  namespace: {{ .Release.Namespace }}
{{ tuple . "localai-env" | include "localai.labels" | indent 2 }}
