apiVersion: v1
data:
{{ tuple . "config/env/worker.env" | include "env.parseFile" | indent 2 }}
kind: ConfigMap
metadata:
  name: worker-env
  namespace: {{ .Release.Namespace }}
{{ tuple . "worker-env" | include "worker.labels" | indent 2 }}
