{{- if .Values.worker.upsertNLPEntities.manualJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: worker-upsert-nlp-entities-manual-{{ now | date "20060102-150405" }}
  namespace: {{ .Release.Namespace }}
{{ tuple . "worker-upsert-nlp-entities-manual" | include "worker.labels" | indent 2 }}
spec:
{{ include "worker.job.spec" (dict "timeout" 1800 "backoffLimit" 2) | indent 2 }}
  template:
    metadata:
{{ tuple . "worker-upsert-nlp-entities-manual" | include "worker.labels" | indent 6 }}
    spec:
{{ include "worker.job.podSpec" . | indent 6 }}
      containers:
        - {{ include "worker.job.container" (dict "name" "worker-upsert-nlp-entities-manual" "command" (list "node" "./build/bin/cli.js" "upsert-nlp-entities") "jobConfig" .Values.worker.upsertNLPEntities.manualJob) | nindent 10 }}
{{- end }}