apiVersion: v1
kind: Service
metadata:
  name: telegram-bot-api
  namespace: {{ .Release.Namespace }}
{{ tuple . "telegram-bot-api" | include "tg.labels" | indent 2 }}
spec:
  ports:
    - name: "8081"
      port: 8081
      protocol: TCP
  selector:
    lies.exposed/name: telegram-bot-api
