apiVersion: v1
data:
  TELEGRAM_API_HASH: {{ .Values.telegram.api.hash }}
  TELEGRAM_API_ID: {{ .Values.telegram.api.id | quote }}
  TELEGRAM_HTTP_IP_ADDRESS: "[::]"
  TELEGRAM_LOCAL: "1"
  TELEGRAM_VERBOSITY: "3"
kind: ConfigMap
metadata:
  name: telegram-bot-api-env
  namespace: {{ .Release.Namespace }}
{{ tuple . "telegram-bot-api-env" | include "tg.labels" | indent 2 }}
