apiVersion: v1
kind: ConfigMap
metadata:
  name: telegram-bot-api-nginx-conf
  namespace: {{ .Release.Namespace }}
{{ tuple . "telegram-bot-api-nginx-conf" | include "tg.labels" | indent 2 }}
data:
{{ if .Files.Get "config/nginx/telegram-bot-api.conf" }}
  telegram-bot-api.conf: |
{{ .Files.Get "config/nginx/telegram-bot-api.conf" | toString | indent 4 }}
{{ else }}
{{ fail "you need to supply your license file! add 'nginx/telegram-bot-api.conf' to your chart 'config' directory." }}
{{ end }}
