apiVersion: v1
data:
  TELEGRAM_API_HASH: {{ .Values.telegram.api.hash }}
  TELEGRAM_API_ID: {{ .Values.telegram.api.id | quote }}
  TG_BOT_BASE_API_URL: http://telegram.liexp-dev.svc.cluster.local:9008
  TG_BOT_CHAT: {{ .Values.telegram.bot.chat | quote }}
  TG_BOT_POLLING: "true"
  TG_BOT_TOKEN: {{ .Values.telegram.bot.token }}
  TG_BOT_USERNAME: {{ .Values.telegram.bot.username }}
kind: ConfigMap
metadata:
  name: telegram-bot-env
  namespace: {{ .Release.Namespace }}
{{ tuple . "telegram-bot-env" | include "tg.labels" | indent 2 }}
