apiVersion: v1
kind: ConfigMap
metadata:
  name: telegram-nginx-conf
  namespace: {{ .Release.Namespace }}
{{ tuple . "telegram-nginx-conf" | include "tg.labels" | indent 2 }}
data:
{{ if .Files.Get "config/nginx/telegram.conf" }}
  telegram.conf: |
{{ .Files.Get "config/nginx/telegram.conf" | toString | indent 4 }}
{{ else }}
{{ fail "you need to supply your license file! add 'nginx/telegram.conf' to your chart 'config' directory." }}
{{ end }}
