apiVersion: v1
data:
data:
{{ tuple . "config/env/ai-bot.env" | include "env.parseFile" | indent 2 }}
kind: ConfigMap
metadata:
  name: ai-bot-env
  namespace: {{ .Release.Namespace }}
{{ tuple . "ai-bot-env" | include "aiBot.labels" | indent 2 }}
