apiVersion: apps/v1
kind: Deployment
metadata:
  name: storybook
  namespace: {{ .Release.Namespace }}
{{ tuple . "storybook" | include "storybook.labels" | indent 2 }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      lies.exposed/name: storybook
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  template:
    metadata:
{{ tuple . "storybook" | include "storybook.labels" | indent 8 }}
    spec:
      containers:
        - image: nginx:1.25.4-alpine
          imagePullPolicy: Always
          name: storybook
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: 256Mi
              cpu: 150m
            requests:
              memory: 128Mi
              cpu: 50m
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: storybook-nginx-conf-storage
              mountPath: /etc/nginx/conf.d/default.conf
              readOnly: false
              subPath: storybook.conf
            - name: storybook-nginx-log
              mountPath: /var/log/nginx
            - name: nginx-cache
              mountPath: /var/cache/nginx/storybook
      restartPolicy: Always
      volumes:
        - name: storybook-nginx-conf-storage
          configMap:
            name: storybook-nginx-conf
            items:
              - key: storybook.conf
                path: storybook.conf
        - name: storybook-nginx-log
          persistentVolumeClaim:
            claimName: storybook-nginx-log-pv-claim
        - name: nginx-cache
          emptyDir:
            sizeLimit: 100Mi
