apiVersion: v1
kind: PersistentVolume
metadata:
  name: storybook-nginx-log
  namespace: {{ .Release.Namespace }}
{{ tuple . "storybook-nginx-log" | include "storybook.labels" | indent 2 }}
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.storybook.nginxLogVolumePath | quote }}
  claimRef:
    name: storybook-nginx-log-pv-claim
    namespace: {{ .Release.Namespace }}
