apiVersion: v1
kind: Service
metadata:
  name: storybook
  namespace: {{ .Release.Namespace }}
{{ tuple . "storybook" | include "storybook.labels" | indent 2 }}
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    lies.exposed/name: storybook
