apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    app.kubernetes.io/part-of: lies-exposed
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    # external-dns.alpha.kubernetes.io/access: public
    # external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    # external-dns.alpha.kubernetes.io/hostname: "admin.{{ .Values.domain }},api.{{ .Values.domain }},www.{{ .Values.domain }}"
    # external-dns.alpha.kubernetes.io/ttl: "60"

spec:
  rules:
    - host: "www.{{ .Values.domain }}"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: web
                port:
                  number: 80
    - host: "api.{{ .Values.domain }}"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: api
                port:
                  number: 80
    - host: "admin.{{ .Values.domain }}"
      http:
        paths:
          - pathType: Prefix
            path: /admin/
            backend:
              service:
                name: admin-web
                port:
                  number: 80
    - host: "telegram.{{ .Values.domain }}"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: telegram
                port:
                  number: 9008
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.domain }}
        - "api.{{ .Values.domain }}"
        - "admin.{{ .Values.domain }}"
      # # cert-manager will create this secret
      # secretName: example-tls

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: load-balancer
#   annotations:
#     external-dns.alpha.kubernetes.io/hostname: lies.exposed
#     external-dns.alpha.kubernetes.io/ttl: "120" #optional
# spec:
#   selector:
#     app: nginx
#   type: LoadBalancer
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80