apiVersion: batch/v1
kind: Job
metadata:
  name: api-migrations
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  {{ tuple . "api-migrations" | include "api.labels" | indent 2 }}
spec:
  activeDeadlineSeconds: 300
  backoffLimit: 1
  template:
    metadata:
{{ tuple . "api-migrations" | include "api.labels" | indent 6 }}
    spec:
      imagePullSecrets:
        - name: ghcr-io-registry-auth
      containers:
        - name: api-migrations
          image: ghcr.io/lies-exposed/liexp-api:alpha-latest
          envFrom:
            - configMapRef:
                name: api-env
          command: ["npx", "typeorm", "migration:run", "-d", "./ormconfig.js"]
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
          tty: true
      restartPolicy: Never
