kind: Secret
apiVersion: v1
metadata:
  name: ghcr-io-registry-auth
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
type: kubernetes.io/dockerconfigjson
