apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: {{ .Release.Namespace }}
{{ tuple . "admin" | include "admin.labels" | indent 2 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      lies.exposed/name: admin
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  template:
    metadata:
{{ tuple . "admin" | include "admin.labels" | indent 8 }}
    spec:
      imagePullSecrets:
        - name: ghcr-io-registry-auth
      containers:
        - image: ghcr.io/lies-exposed/liexp-admin:latest
          envFrom:
            - configMapRef:
                name: admin-env
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 4010
            failureThreshold: 10
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 20
          name: admin
          ports:
            - containerPort: 4010
              protocol: TCP
          resources:
            limits:
              memory: 256Mi
              cpu: 150m
            requests:
              memory: 128Mi
              cpu: 50m
          # tty: true
          {{- if .Values.admin.dev -}}
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: admin-build
          {{- end -}}
      restartPolicy: Always
      # {{- if .Values.admin.dev -}}
      # volumes:
      #   - name: admin-build
      #     persistentVolumeClaim:
      #       claimName: admin-build-pv-claim
      # {{- end -}}
