apiVersion: v1
data:
{{ tuple . "config/env/admin.server.env" | include "env.parseFile" | indent 2 }}
kind: ConfigMap
metadata:
{{ tuple . "admin-env" | include "admin.labels" | indent 2 }}
  name: admin-env