apiVersion: v1
kind: Service
metadata:
  name: admin
{{ tuple . "admin" | include "admin.labels" | indent 2 }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4010
  selector:
    lies.exposed/name: admin
    app.kubernetes.io/instance: {{ .Release.Name | quote }}