{{- if .Values.adminWeb.dev -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: admin-web-build-pv-claim
  namespace: {{ .Release.Namespace }}
  {{ tuple . "admin-web-build-pv-claim" | include "adminWeb.labels" | indent 2 }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      lies.exposed/name: admin-web-build-volume
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/namespace: {{ .Release.Namespace | quote }}
{{- end -}}
