apiVersion: v1
data:
  VIRTUAL_HOST: "admin.{{ .Values.domain }}"
  VIRTUAL_PORT: "80"
  VITE_API_URL: "https://api.{{ .Values.domain }}/v1"
  VITE_DATA_URL: "https://fra1.space.{{ .Values.domain }}"
  VITE_DEBUG: "@liexp:*"
  VITE_NODE_ENV: production
  VITE_OPENAI_URL: "https://localai.{{ .Values.domain }}:8080/v1"
  VITE_PUBLIC_URL: "https://admin.{{ .Values.domain }}"
  VITE_WEB_URL: "https://{{ .Values.domain }}"
kind: ConfigMap
metadata:
  name: admin-web-env
{{ tuple . "admin-web-env" | include "adminWeb.labels" | indent 2 }}
