apiVersion: v1
data:
{{ tuple . "config/env/admin-web.server.env" | include "env.parseFile" | indent 2 }}
kind: ConfigMap
metadata:
{{ tuple . "admin-web-env" | include "adminWeb.labels" | indent 2 }}
  name: admin-web-env