name: Pull Request

on:
  pull_request:
    branches:
      - release/alpha
      - master
    paths:
      - "packages/**"
      - "services/api/**"
      - "services/admin-web/**"
      - "services/web/**"

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # - uses: actions/cache@v2
      #   with:
      #     path: "**/node_modules"
      #     key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install modules
        # if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn

      - name: List modules
        run: yarn list

  lint:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Lint code
        run: yarn lint

  build-api:
    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Build api
        run: yarn workspace api build

      - name: Upload API build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            packages/@econnessione/**/lib
            services/api/build

  build-admin-web:
    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Build admin-web
        run: yarn workspace admin-web build
        env:
          DISABLE_ESLINT_PLUGIN: true
          SKIP_PREFLIGHT_CHECK: true

      - name: Upload admin-web build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            packages/@econnessione/**/lib
            services/admin-web/build

  build-web:
    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Build web
        run: yarn workspace web build
        env:
          DISABLE_ESLINT_PLUGIN: true
          SKIP_PREFLIGHT_CHECK: true

      - name: Upload web build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            packages/@econnessione/**/lib
            services/web/build

  tests-spec:
    runs-on: ubuntu-latest
    needs: [lint, build-api, build-admin-web, build-web]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Run tests SPEC
        run: yarn test:spec

  tests-e2e:
    runs-on: ubuntu-latest
    needs: [lint, build-api, build-admin-web, build-web]
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: econnessione
          POSTGRES_PASSWORD: econnessione-password
          POSTGRES_DB: econnessione-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 9432:5432
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Run tests E2E
        run: yarn test:e2e --ci --forceExit
